#!/bin/sh
#
# @name Generic VTOL TVMD (SITL) : H-frame, 4x ducted fan + 8x tilting servos
#
# @type VTOL TVMD
#
# @maintainer Sciyen <sciyen.ycc@gmail.com>
# @maintainer FKC <d12921b11@ntu.edu.tw>
#

. ${R}etc/init.d/rc.tvmd_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=tvmd}

param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 0
param set-default SENS_EN_MAGSIM 1
param set-default SENS_EN_ARSPDSIM 1

# TODO: Enable motor failure detection when the
# VTOL no longer reports 0A for all ESCs in SITL
param set-default FD_ACT_EN 0
param set-default FD_ACT_MOT_TOUT 500

param set-default MAV_TYPE 21

param set-default CA_AIRFRAME 13
param set-default CA_METHOD 3

# Motor idle and throttle settings
param set-default MPC_THR_MIN 0.10      # Minimum throttle (10% when armed)
param set-default MPC_THR_HOVER 0.50    # Expected hover throttle (50%)
param set-default MPC_MANTHR_MIN 0.05   # Manual mode minimum throttle
param set-default COM_DISARM_PRFLT 10   # Disarm timeout for preflight check (10s)

# Module settings - H-frame configuration (match hardware: L=0.185m, W=0.16m)
param set-default CA_MD_COUNT 4

param set-default CA_MD0_PX 0.185      # Front-Left
param set-default CA_MD0_PY 0.16
param set-default CA_MD0_PZ 0
param set-default CA_MD0_AZ 0          # All modules same orientation
param set-default CA_MD0_X_GR 1.0
param set-default CA_MD0_Y_GR 1.0

param set-default CA_MD1_PX 0.185      # Front-Right
param set-default CA_MD1_PY -0.16
param set-default CA_MD1_PZ 0
param set-default CA_MD1_AZ 0          # All modules same orientation
param set-default CA_MD1_X_GR 1.0
param set-default CA_MD1_Y_GR 1.0

param set-default CA_MD2_PX -0.185     # Rear-Left
param set-default CA_MD2_PY 0.16
param set-default CA_MD2_PZ 0
param set-default CA_MD2_AZ 0
param set-default CA_MD2_X_GR 1.0
param set-default CA_MD2_Y_GR 1.0

param set-default CA_MD3_PX -0.185     # Rear-Right
param set-default CA_MD3_PY -0.16
param set-default CA_MD3_PZ 0
param set-default CA_MD3_AZ 0
param set-default CA_MD3_X_GR 1.0
param set-default CA_MD3_Y_GR 1.0

# Rotor settings - Single propeller H-frame (4 motors)
param set-default CA_ROTOR_COUNT 4

# Motor 0 (Module 0, Front-Left, CW)
param set-default CA_ROTOR0_CT 0.012   # Match hardware thrust coefficient
param set-default CA_ROTOR0_KM -0.0188 # CW rotation
param set-default CA_ROTOR0_PX 0
param set-default CA_ROTOR0_PY 0
param set-default CA_ROTOR0_PZ 0.0     # Single prop at module center
param set-default CA_ROTOR0_TILT 1

# Motor 1 (Module 1, Front-Right, CCW)
param set-default CA_ROTOR1_CT 0.012
param set-default CA_ROTOR1_KM 0.0188  # CCW rotation
param set-default CA_ROTOR1_PX 0
param set-default CA_ROTOR1_PY 0
param set-default CA_ROTOR1_PZ 0.0
param set-default CA_ROTOR1_TILT 2

# Motor 2 (Module 2, Rear-Left, CCW)
param set-default CA_ROTOR2_CT 0.012
param set-default CA_ROTOR2_KM 0.0188  # CCW rotation
param set-default CA_ROTOR2_PX 0
param set-default CA_ROTOR2_PY 0
param set-default CA_ROTOR2_PZ 0.0
param set-default CA_ROTOR2_TILT 3

# Motor 3 (Module 3, Rear-Right, CW)
param set-default CA_ROTOR3_CT 0.012
param set-default CA_ROTOR3_KM -0.0188 # CW rotation
param set-default CA_ROTOR3_PX 0
param set-default CA_ROTOR3_PY 0
param set-default CA_ROTOR3_PZ 0.0
param set-default CA_ROTOR3_TILT 4

# Tilting servos - All ±45° configuration (circular cone LAFS)
param set-default CA_SV_TL_COUNT 8

param set-default CA_SV_TL0_MINA -45   # Module 0, X-axis
param set-default CA_SV_TL0_MAXA 45
param set-default CA_SV_TL0_TD 0
param set-default CA_SV_TL0_CT 1

param set-default CA_SV_TL1_MINA -45   # Module 0, Y-axis
param set-default CA_SV_TL1_MAXA 45
param set-default CA_SV_TL1_TD 90
param set-default CA_SV_TL1_CT 1

param set-default CA_SV_TL2_MINA -45   # Module 1, X-axis
param set-default CA_SV_TL2_MAXA 45
param set-default CA_SV_TL2_TD 0
param set-default CA_SV_TL2_CT 1

param set-default CA_SV_TL3_MINA -45   # Module 1, Y-axis
param set-default CA_SV_TL3_MAXA 45
param set-default CA_SV_TL3_TD 90
param set-default CA_SV_TL3_CT 1

param set-default CA_SV_TL4_MINA -45   # Module 2, X-axis
param set-default CA_SV_TL4_MAXA 45
param set-default CA_SV_TL4_TD 0
param set-default CA_SV_TL4_CT 1

param set-default CA_SV_TL5_MINA -45   # Module 2, Y-axis
param set-default CA_SV_TL5_MAXA 45
param set-default CA_SV_TL5_TD 90
param set-default CA_SV_TL5_CT 1

param set-default CA_SV_TL6_MINA -45   # Module 3, X-axis
param set-default CA_SV_TL6_MAXA 45
param set-default CA_SV_TL6_TD 0
param set-default CA_SV_TL6_CT 1

param set-default CA_SV_TL7_MINA -45   # Module 3, Y-axis
param set-default CA_SV_TL7_MAXA 45
param set-default CA_SV_TL7_TD 90
param set-default CA_SV_TL7_CT 1

# Gazebo Simulation Output Settings
param set-default SIM_GZ_EN 1

# Motor outputs (4 motors)
param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104

param set-default SIM_GZ_EC_MIN1 0
param set-default SIM_GZ_EC_MIN2 0
param set-default SIM_GZ_EC_MIN3 0
param set-default SIM_GZ_EC_MIN4 0

param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_MAX2 1000
param set-default SIM_GZ_EC_MAX3 1000
param set-default SIM_GZ_EC_MAX4 1000

# Servo outputs (8 servos)
param set-default SIM_GZ_SV_FUNC1 201
param set-default SIM_GZ_SV_FUNC2 202
param set-default SIM_GZ_SV_FUNC3 203
param set-default SIM_GZ_SV_FUNC4 204
param set-default SIM_GZ_SV_FUNC5 205
param set-default SIM_GZ_SV_FUNC6 206
param set-default SIM_GZ_SV_FUNC7 207
param set-default SIM_GZ_SV_FUNC8 208
