#!/bin/bash

echo "========================================"
echo "  TVMD 舵機輸出驗證工具"
echo "========================================"
echo ""

# 檢查是否有 PX4 SITL 在運行
if ! pgrep -f "px4.*sitl" > /dev/null; then
    echo "❌ 錯誤: PX4 SITL 未運行"
    echo ""
    echo "請先啟動 SITL:"
    echo "  ./launch_tvmd_headless.sh"
    exit 1
fi

echo "✅ 檢測到 PX4 SITL 正在運行"
echo ""

# 檢查 Gazebo
if ! pgrep -f "gz sim" > /dev/null; then
    echo "⚠️  警告: 未檢測到 Gazebo，可能使用了非 GUI 模式"
fi

echo "========================================"
echo " 選項 1: 在 PX4 Console 查看輸出"
echo "========================================"
echo ""
echo "請在 PX4 SITL 終端的 pxh> 提示符下輸入："
echo ""
echo "  listener actuator_outputs"
echo ""
echo "您應該會看到類似："
echo "  output[0]: 150    # Motor 1"
echo "  output[1]: 150    # Motor 2"
echo "  output[2]: 150    # Motor 3"
echo "  output[3]: 150    # Motor 4"
echo "  output[4]: 500    # Servo 1 (Tilt 1 X)"
echo "  output[5]: 500    # Servo 2 (Tilt 1 Y)"
echo "  ..."
echo ""
echo "數值範圍："
echo "  - 馬達: 0-1000 (0-100%)"
echo "  - 舵機: 0-1000 (對應 -45° 到 +45°, 500=0°)"
echo ""

echo "========================================"
echo " 選項 2: 監控 Gazebo Topics"
echo "========================================"
echo ""
echo "在當前終端或新終端運行以下命令："
echo ""
echo "# 列出所有 TVMD 相關 topics"
echo "gz topic -l | grep tvmd"
echo ""
echo "# 監聽特定舵機 (Ctrl+C 停止)"
echo "gz topic -e -t /model/tvmd/servo_0"
echo ""
echo "# 查看所有舵機指令"
echo "for i in {0..7}; do"
echo "  echo \"Servo \$i:\""
echo "  gz topic -e -t /model/tvmd/servo_\$i -n 1"
echo "done"
echo ""

echo "========================================"
echo " 為什麼 QGC 顯示全 0？"
echo "========================================"
echo ""
echo "這是正常的！原因："
echo ""
echo "✓ SERVO_OUTPUT_RAW 是硬體 PWM 輸出消息"
echo "✓ Gazebo SITL 不使用 PWM，而是直接通訊"
echo "✓ 實際數據在 actuator_outputs uORB topic"
echo "✓ Gazebo 通過 gz-transport 接收舵機指令"
echo ""
echo "解決方法："
echo "→ 使用上面的「選項 1」或「選項 2」查看實際輸出"
echo ""

echo "========================================"
echo " 測試舵機是否在動？"
echo "========================================"
echo ""
echo "1. 確保 SITL 已 armed (解鎖)"
echo "2. 在 QGC 中給予姿態指令（搖桿或任務）"
echo "3. 觀察 Gazebo 中舵機是否轉動"
echo ""
echo "如果舵機在 Gazebo 中轉動 = 工作正常！"
echo "QGC 顯示 0 不影響實際功能。"
echo ""
